export default {
    DourBellLgo: require("./Image/dourbelllogo.png"),
    DourBellHeader:require('./Image/duarbellHeader.png'),
    DuarBellMenu:require("./Image/DuarBellMenu.png"),
    DuarBellSrarch:require('./Image/DuarBellSrarch.png'),
    Location:require('./Image/Location.png'),
    Message:require('./Image/Message.png'),
    Notifications:require('./Image/Notifications.png'),
    DuarbellCall:require('./Image/DuarbellCall.png'),
    Intro1:require('./Image/Intro.png'),
    Intro2:require('./Image/IntroScreen.png'),
    CommonBackgroundImage:require('./Image/CommonBackgroundImage.png'),
    homeImage:require('./Image/homeImage.png'),
    tabHome: require('./Image/homeIcon.png'),
    tabOutline: require('./Image/outLineTag.png'),
    tabFavroite: require('./Image/favroiteIcon.png'),
    tabWallet: require('./Image/walletIcon.png'),
    tabUser: require('./Image/userIcon.png'),
    tools: require('./Image/Tools.png'),
    banner: require('./Image/banner.png'),
    adds: require('./Image/ads.png'),
    serviceMan: require('./Image/serviceManImage.png'),
    Userprofile:require('../assets/Image/Userprofile.png'),
    verified:require('../assets/Image/verified.png'),
    star:require('../assets/Image/star.png'),
    calender:require('../assets/Image/calender.png'),
    phone:require('../assets/Image/phone.png'),
    fav:require('../assets/Image/fav.png'),
    dropdown:require('../assets/Image/dropdown.png'),
    mic: require('../assets/Image/mic.png'),
    linearView: require('../assets/Image/linearView.png'),
    bell: require('../assets/Image/bell.png'),
    fadeBell: require('../assets/Image/fadeBell.png'),
    dotVertical: require('../assets/Image/dotVertical.png'),
    Vector:require('../assets/Image/Vector.png'),
    eye:require('../assets/Image/eye.png'),
    edit:require('../assets/Image/edit.png'),
    arrow: require('../assets/Image/arrow.png'),
    useraccount:require('../assets/Image/useraccount.png'),
    transaction:require('../assets/Image/transaction.png'),
    solarpassword:require('../assets/Image/solarpassword.png'),
    notificationalarm:require('../assets/Image/notificationalarm.png'),
    camera:require('../assets/Image/camera.png'),
    banner2: require('./Image/banner2.png'),
    portfolio: require('../assets/Image/portfolio.png'),
    service2: require('../assets/Image/service2.png'),
    wallet2: require('../assets/Image/phwallet.png'),
    plans: require('../assets/Image/cashflow.png'),
    manageBook: require('../assets/Image/outlinetag2.png'),
    review: require('../assets/Image/starreview.png'),
    managestuff: require('../assets/Image/phusers.png'),
    profile:require('../assets/Image/profile.png'),
    idvarification: require('../assets/Image/outline.png'),
    setting: require('../assets/Image/setting.png'),
}