export const NAVIGATION_AUTH_LOADING: string =
  "NAVIGATION_AUTH_LOADING";
export const NAVIGATION_AUTH_FLOW: string =
  "NAVIGATION_AUTH_FLOW"
export const NAVIGATION_LOGIN: string =
  "NAVIGATION_LOGIN"
export const NAVIGATION_INTRO: string =
  "NAVIGATION_INTRO"

export const NAVIGATION_HONE_STACK: string =
  "NAVIGATION_HONE_STACK"
export const TAB_NAVIGATION: string =
  "TAB_NAVIGATION"
export const NAVIGATION_HOME_SCREEN: string =
  "NAVIGATION_HOME_SCREEN"

export const NAVIGATION_DASHBOARD_STACK: string =
  "NAVIGATION_DASHBOARD_STACK"

export const NAVIGATION_BOOKING_SCREEN: string =
  "NAVIGATION_BOOKING_SCREEN"

export const NAVIGATION_FAVORITE_SCREEN: string =
  "NAVIGATION_FAVORITE_SCREEN"

export const NAVIGATION_WALEET_SCREEN: string =
  "NAVIGATION_WALEET_SCREEN"

export const NAVIGATION_USER_SCREEN: string =
  "NAVIGATION_USER_SCREEN"

export const NAVIGATION_MESSAGE_SCREEN: string =
  "NAVIGATION_MESSAGE_SCREEN"
export const NAVIGATION_NOTIFICATION_SCREEN: string =
  "NAVIGATION_NOTIFICATION_SCREEN"
export const NAVIGATION_CALL_LOG_SCREEN: string =
  "NAVIGATION_CALL_LOG_SCREEN"
export const NAVIGATION_SEARCH_SCREEN: string =
  "NAVIGATION_SEARCH_SCREEN"

export const NAVIGATION_SERVICE_LIST_SCREEN: string =
  "NAVIGATION_SERVICE_LIST_SCREEN"

export const NAVIGATION_LIST_SCREEN: string =
  "NAVIGATION_LIST_SCREEN"

export const NAVIGATION_HOME_BOTTOM_STACK: string =
  "NAVIGATION_HOME_BOTTOM_STACK"
export const NAVIGATION_BOOKING_BOTTOM_STACK: string =
  "NAVIGATION_BOOKING_BOTTOM_STACK"
export const NAVIGATION_FAVORITE_BOTTOM_STACK: string =
  "NAVIGATION_FAVORITE_BOTTOM_STACK"
export const NAVIGATION_WALLET_BOTTOM_STACK: string =
  "NAVIGATION_WALLET_BOTTOM_STACK"
export const NAVIGATION_USER_BOTTOM_STACK: string =
  "NAVIGATION_USER_BOTTOM_STACK "
export const NAVIGATION_CALLHISTORY: string =
  "NAVIGATION_CALLHISTORY"

export const NAVIGATION_VERIFICATION_ONE: string =
  "NAVIGATION_VERIFICATION_ONE"

export const NAVIGATION_MANAGE_BOOK_THREE: string =
  "NAVIGATION_MANAGE_BOOK_THREE"

export const NAVIGATION_MYACCOUNTS: string =
  "NAVIGATION_MYACCOUNTS"

export const NAVIGATION_EDITPROFILE: string =
  "NAVIGATION_EDITPROFILE"

export const NAVIGATION_PROVIDERPROFILE: string =
  "NAVIGATION_PROVIDERPROFILE"

export const NAVIGATION_BELLCOINS: string =
  "NAVIGATION_BELLCOINS"

export const NAVIGATION_PROVIDER_DETAIL: string =
  "NAVIGATION_PROVIDER_DETAIL"

export const NAVIGATION_PROVIDER_STACK: string =
  "NAVIGATION_PROVIDER_STACK"

export const USER_STACK: string =
  "USER_STACK"

  export const NAVIGATION_WALEET2: string =
  "NAVIGATION_WALEET2"

  export const NAVIGATION_PLANS: string =
  "NAVIGATION_PLANS"

  export const NAVIGATION_ACTIVE_PLAN_SCREEN: string =
  "NAVIGATION_ACTIVE_PLAN_SCREEN"

  export const NAVIGATION_MANAGE_REVIEWS: string =
  "NAVIGATION_MANAGE_REVIEWS"

  export const NAVIGATION_MANAGE_BOOKING_ONE: string =
  "NAVIGATION_MANAGE_BOOKING_ONE"

  
  export const NAVIGATION_ADD_STAFF: string =
  "NAVIGATION_ADD_STAFF"

  export const NAVIGATION_MY_PORTFOLIO: string =
  "NAVIGATION_MY_PORTFOLIO"
  
  export const NAVIGATION_PROVIDER_PROFILE_DETAIL: string =
  "NAVIGATION_PROVIDER_PROFILE_DETAIL"

  export const NAVIGATION_PROFILE_GRANTER: string =
  "NAVIGATION_PROFILE_GRANTER"

  export const NAVIGATION_MANAGE_SERVICE: string =
  "NAVIGATION_MANAGE_SERVICE"