export const NAVIGATION_AUTH_LOADING: string =
  "NAVIGATION_AUTH_LOADING";
  export const NAVIGATION_AUTH_FLOW: string =
  "NAVIGATION_AUTH_FLOW"
  export const NAVIGATION_LOGIN: string =
  "NAVIGATION_LOGIN"
  export const NAVIGATION_INTRO: string =
  "NAVIGATION_INTRO"

  export const NAVIGATION_HONE_STACK: string =
  "NAVIGATION_HONE_STACK"
  export const NAVIGATION_DASHBOARD_STACK: string =
  "NAVIGATION_DASHBOARD_STACK"
  export const NAVIGATION_HOME_SCREEN: string =
  "NAVIGATION_HOME_SCREEN"

  export const NAVIGATION_BOOKING_SCREEN: string =
  "NAVIGATION_BOOKING_SCREEN"

  export const NAVIGATION_FAVORITE_SCREEN: string =
  "NAVIGATION_FAVORITE_SCREEN"

  export const NAVIGATION_WALEET_SCREEN: string =
  "NAVIGATION_WALEET_SCREEN"

  export const NAVIGATION_USER_SCREEN: string =
  "NAVIGATION_USER_SCREEN"

  export const NAVIGATION_MESSAGE_SCREEN: string =
  "NAVIGATION_MESSAGE_SCREEN"
  export const NAVIGATION_NOTIFICATION_SCREEN: string =
  "NAVIGATION_NOTIFICATION_SCREEN"
  export const NAVIGATION_CALL_LOG_SCREEN: string =
  "NAVIGATION_CALL_LOG_SCREEN"
  export const NAVIGATION_SEARCH_SCREEN: string =
  "NAVIGATION_SEARCH_SCREEN"

  export const NAVIGATION_SERVICE_LIST_SCREEN: string =
  "NAVIGATION_SERVICE_LIST_SCREEN"

  export const NAVIGATION_LIST_SCREEN: string =
  "NAVIGATION_LIST_SCREEN"

  export const NAVIGATION_HOME_BOTTOM_STACK: string =
  "NAVIGATION_HOME_BOTTOM_STACK"
  export const NAVIGATION_BOOKING_BOTTOM_STACK: string =
  "NAVIGATION_BOOKING_BOTTOM_STACK" 
  export const NAVIGATION_FAVORITE_BOTTOM_STACK: string =
  "NAVIGATION_FAVORITE_BOTTOM_STACK"
  export const NAVIGATION_WALLET_BOTTOM_STACK: string =
  "NAVIGATION_WALLET_BOTTOM_STACK"  
  export const NAVIGATION_USER_BOTTOM_STACK: string =
  "NAVIGATION_USER_BOTTOM_STACK "
  export const NAVIGATION_CALLHISTORY: string =
  "NAVIGATION_CALLHISTORY"

  export const NAVIGATION_VERIFICATION_ONE: string =
  "NAVIGATION_VERIFICATION_ONE"

  export const NAVIGATION_MANAGE_BOOK_THREE: string =
  "NAVIGATION_MANAGE_BOOK_THREE"

  export const NAVIGATION_MYACCOUNTS: string =
  "NAVIGATION_MYACCOUNTS"

  export const NAVIGATION_EDITPROFILE: string =
  "NAVIGATION_EDITPROFILE"

  export const NAVIGATION_PROVIDERPROFILE: string=
  "NAVIGATION_PROVIDERPROFILE"